# Generated by Django 2.1 on 2020-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateID', models.CharField(max_length=20)),
                ('CandidateName', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
